### ISSUE TITLE
User Section

### ISSUE THREAD

**Issue by Jashika** [Offcampus4u/offcampus4u.github.io#10]
1.User login form must appear first rather than Account Creation form.
2.Multiple mail being sent as soon i click on the link "**click here to activate your account**"
3.Entering Profile details- Field validation is needed.
4.Under Education details-Either notify users to enter more than three characters or allow minimum three characters to be entered(Because if user specifies BCA or MBA as their degree it creates problem to save)
5.Password Change(User Profile)-The Password field can be changed to Re-enter new password
6.Password change and updated mail-No mail is being recieved while password change and updated
7. User/profile/education -More fields need to be added 
7.User/job-job type search fields must be changed and its not working

**Comment by gauravbansal74** [comment]
1. User login form must appear first rather than Account Creation form. - Done

**Comment by gauravbansal74** [comment]
3. Entering Profile details- Field validation is needed. - Done

**Comment by gauravbansal74** [comment]
4. .Under Education details-Either notify users to enter more than three characters or allow minimum three characters to be entered(Because if user specifies BCA or MBA as their degree it creates problem to save) - can't be done - because there is BE course also.

**Comment by gauravbansal74** [comment]
5.Password Change(User Profile)-The Password field can be changed to Re-enter new password - Done

**Comment by gauravbansal74** [comment]
Password change and updated mail-No mail is being recieved while password change and updated - Done

**Comment by gauravbansal74** [comment]
User/job-job type search fields must be changed and its not working - Done

**Comment by gauravbansal74** [comment]
User/job-job type search fields must be changed and its not working - Done ( Value changed form sugar CRM and its working fine now)
