### ISSUE TITLE
Employer Section

### ISSUE THREAD

**Issue by Jashika** [Offcampus4u/offcampus4u.github.io#11]
1.Employer Account/settings-Password field change it to Re-enter new password
2.Password change updates- the employer must receive mail ,Mail is not received
3.Employer/Dashboard/Candidates-Location field is empty
4.Employer/Dashboard/Candidates/Resume-Mobile field is empty
5.Employer/Dashboard/Candidates/Resume/Schedule interview-Date must not accept previous date, But its allowed.
6.Employer/Dashboard/Candidates/Resume/Schedule interview-interviews field is accepting invalid email-address
7.Any mails received for the candidate ,when the particular link is clicked it goes nowhere(not taking to related contents like message,status change, scheduled interview...)
8. Number and text field validations required while entering mobile no,name in both employer/user.

**Comment by gauravbansal74** [comment]
Employer Account/settings-Password field change it to Re-enter new password - Done

**Comment by gauravbansal74** [comment]
2.Password change updates- the employer must receive mail ,Mail is not received - Done

**Comment by gauravbansal74** [comment]
Employer/Dashboard/Candidates-Location field is empty - its working fine. it user entered location value.

**Comment by gauravbansal74** [comment]
Employer/Dashboard/Candidates/Resume-Mobile field is empty - Not saved in DB

**Comment by gauravbansal74** [comment]
Whatever is left .. its not possible in this version for that we have to modified so much code.

**Comment by gauravbansal74** [comment]
Done
