### ISSUE TITLE
Noted issues

### ISSUE THREAD

**Issue by Jashika** [Offcampus4u/offcampus4u.github.io#12]
1.Session is not getting timed out, its always logged in.
2.Employer/create jobs validation is required  for position ,department ,state and city field
3.Employer/view job Apply job (hope its not needed).
4.First time when user  applies for the job ,notification should be **you have applied for this job**, but its showing **you have already applied for this job.**
5.Employer/Schedule interview -candidate mobile no ,interviewers field must be validated
6.Employer/Schedule interview-Date selection accepting previous date .

**Comment by gauravbansal74** [comment]
Employer/Schedule interview -candidate mobile no ,interviewers field must be validated - Done

**Comment by gauravbansal74** [comment]
Employer/Schedule interview-Date selection accepting previous date . - Done

**Comment by gauravbansal74** [comment]
4.First time when user applies for the job ,notification should be you have applied for this job, but its showing you have already applied for this job. - Done

**Comment by gauravbansal74** [comment]
.Employer/view job Apply job (hope its not needed). - @Jashika Please explain

**Comment by gauravbansal74** [comment]
Employer/create jobs validation is required for position ,department ,state and city field - Done
