### ISSUE TITLE
Subject for emails

### ISSUE THREAD

**Issue by Jashika** [Offcampus4u/offcampus4u.github.io#2]
The Subject must be changed from "Password change request" to "Reset your Offcampus4u password"
Subject "Offcampus4u: **You** account activated." to be changed to "Offcampus4u account activated" or "Your Offcampus4u account activated"
Subject "Offcampus4u:  You account password successfully updated." to be changed to "Password change for your Offcampus4u account"
Subject "Offcampus4u: Application Status Changed." to be changed to "Offcampus4u: Application status changed"
Subject "Offcampus4u: Candidate Applied." to be changed to "Offcampus4u: Application received for vacancy"

**Comment by gauravbansal74** [comment]
Done - Minor changes .. because we have to keep all the subject in similar format.

- Offcampus4u: Your account activated.

- Offcampus4u: Reset your account password

**Comment by gauravbansal74** [comment]
Offcampus4u: Password changed for your account

Offcampus4u: Application status changed

Offcampus4u: Application received for vacancy
