### ISSUE TITLE
Important issues

### ISSUE THREAD

**Issue by Jashika** [Offcampus4u/offcampus4u.github.io#20]
1.Employer section-Skills with two, one characters like c, c#  is not accepted but c++ is accepted.
2.User section-experience field displayed should have < or > symbol
3.User section-Three keyword search not working
4.User section-search based on salary, location,industry :under left navigation search its showing non-existing location,industry,salary rather than existing one
5.Employer section-schedule interview mail is not received by the candidate
6.User section-Interviews not getting updated
7.Employer section-No review mail is sent to the candidate
8.Employer section-Message mail not sent nor updated 
9.User section-No message updates
10.Employer section/Schedule interview/interviewers-Mail id must be specified and also if the interviewer is already part of the portal  his name must be popped out
11.No Dashboard Updates
11.Employer /Organization-Mail is not sent to the interviewer/recruiter being added
12.Employer/Organization-Once members added there is no option for editing those members phone number, other related fields.

**Comment by gauravbansal74** [comment]
They can't update user details - 
12.Employer/Organization: Once members added there is no option for editing those members phone number, other related fields - Done

**Comment by gauravbansal74** [comment]
11.Employer /Organization-Mail is not sent to the interviewer/recruiter being added - Working Please check

**Comment by gauravbansal74** [comment]
11.No Dashboard Updates - Done

**Comment by gauravbansal74** [comment]
.User section-No message updates - Done

**Comment by gauravbansal74** [comment]
Employer section-Message mail not sent nor updated  - Working fine

**Comment by gauravbansal74** [comment]
User section-Interviews not getting updated - Working fine

**Comment by gauravbansal74** [comment]
5.Employer section-schedule interview mail is not received by the candidate  - Working fine

**Comment by gauravbansal74** [comment]
2.User section-experience field displayed should have < or > symbol - Done
